Task 19 (Chat)
Project-Stage-Academy/ChNU-Practics-2024 pull request #49
Opened 2024-02-25 22:23 UTC by BoikoAleks

2024-02-26 08:05 UTC, ivtka commented
Resolve conflicts to kick off the PR review

2024-02-26 08:18 UTC, ivtka commented
LGTM for other changes

2024-02-26 08:20 UTC, ivtka commented
And some point: the chat doesn't need to be stored in the database, right?

2024-02-27 15:11 UTC, mehalyna commented
Add ```.idea``` to ```.gitignore```, pls

2024-02-27 16:09 UTC, mehalyna requested changes

2024-02-27 16:09 UTC, mehalyna commented on src/apps/authentication/serializers.py
> +        self.token = attrs('refresh')
The way you're trying to access ```refresh``` from ```attrs``` seems incorrect. ```attrs``` is a dictionary, so you should use square brackets to access its elements: ```self.token = attrs['refresh']```

2024-02-27 16:09 UTC, mehalyna commented on src/apps/authentication/serializers.py
> +        return attrs
It's generally a good practice to include some form of validation inside the ```validate``` method. If you're only setting the token here, consider renaming this method to something more descriptive, or perform the token validation here to ensure it's a well-formed token before proceeding to the ```save``` method

2024-02-27 16:09 UTC, mehalyna commented on src/apps/authentication/serializers.py
> +            self.fail('bad_token')
After successfully blacklisting the token, consider if there's any additional cleanup or response handling needed. For example, you might want to return a success message or status code to indicate the logout was successful

2024-02-27 16:09 UTC, mehalyna commented on src/apps/authentication/views.py
> +        return Response(status=status.HTTP_204_NO_CONTENT)
While HTTP 204 is appropriate, depending on your frontend requirements, you might want to return a JSON response with a success message or additional data. In such cases, you can use HTTP 200 OK and include a response body

2024-02-27 16:09 UTC, mehalyna commented on src/chat/consumers.py
> +        self.room_group_name = "chat_%s" % self.room_name
Consider using f-strings for string formatting, as they are more readable and efficient than the % operator: ```self.room_group_name = f"chat_{self.room_name}"```

2024-02-27 19:09 UTC, ivtka requested changes

2024-02-27 19:09 UTC, ivtkac commented on .idea/.gitignore
Make sure you not run `git add .` otherwise you'll adding files unrelated to the changes.

2024-02-27 19:09 UTC, ivtkac commented on src/apps/authentication/serializers.py
Rebase against the develop branch required

2024-02-27 19:09 UTC, ivtkac commented on src/apps/authentication/urls.py
Same here, it's already merged into the develop branch

2024-02-27 19:09 UTC, ivtkac commented on src/chat/consumers.py
Shift this `chat` app to the `apps/` directory for a project structure appearance

2024-03-04 12:49 UTC, ivktac commented
I think this pr can be rejected due to the technical problems and feature freeze

2024-03-04 12:49 UTC, closed without merging